# Generated by Django 3.2 on 2022-09-11 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=32)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('upload_date', models.DateTimeField()),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='study.genre')),
            ],
        ),
    ]
