# Generated by Django 3.2 on 2022-09-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_alter_genre_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='genre/'),
        ),
    ]
