# Generated by Django 3.2 on 2022-09-12 08:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20220912_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(default='No description', max_length=100),
        ),
        migrations.AddField(
            model_name='genre',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='text',
            name='description',
            field=models.TextField(default='No description', max_length=100),
        ),
        migrations.AddField(
            model_name='text',
            name='text',
            field=models.FileField(default='', upload_to='text/textfile', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'MPEG4', 'mp4'])]),
        ),
        migrations.AlterField(
            model_name='genre',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='genre/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='text',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='text/img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg'])]),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(default='', max_length=200)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='study.text')),
            ],
        ),
    ]
