# Generated by Django 3.2 on 2022-11-28 07:05

import django.core.validators
from django.db import migrations, models
import study.models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_reply_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.FileField(default='', upload_to='text/textfile', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'MPEG4', 'mp4']), study.models.validate_max_size]),
        ),
    ]
