# Generated by Django 3.2 on 2022-11-28 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_auto_20221128_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
